<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-HL4JRJF" failures="1" tests="2" name="Default test(failed)(failed)" time="0.067" errors="0" timestamp="2022-09-08T19:37:03 IST">
  <testcase classname="com.qa.demo.RetryFailedDemo" name="test2" time="0.009"/>
  <testcase classname="com.qa.demo.RetryFailedDemo" name="test3" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.qa.demo.RetryFailedDemo.test3(RetryFailedDemo.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="com.qa.demo.RetryFailedDemo" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed)(failed) -->
